import type { Metadata } from "next";
import { Marhey } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "./context/DarkMode";
import NavBar from "./components/NavBar";

const marhey = Marhey({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${marhey.className}  bg-white dark:bg-[#03102b]`}>
      <DarkModeProvider>
          <NavBar/>
          {children}
      </DarkModeProvider>
          </body>
    </html>
  );
}
